version: '3.9'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - api-test
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    networks:
      - api-test
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  clients:
    build: ./clients
    ports:
      - '3001:3001'
    networks:
      - api-test

  bills:
    build: ./bills
    ports:
      - '3002:3002'
    networks:
      - api-test
    depends_on:
      - kafka

  orders:
    build: ./orders
    ports:
      - '3003:3003'
    networks:
      - api-test
    depends_on:
      - kafka

  api_gateway:
    build: ./apiGateway
    ports:
      - '8000:8000'
    networks:
      - api-test
    depends_on:
      - clients
      - bills
      - orders

networks:
  api-test:
    driver: bridge

volumes:
  kafka: